development:
  adapter: postgresql
  database: michaelcalhoun_development
  username: michaelcalhoun
  password:

test:
  adapter: postgresql
  database: michaelcalhoun_test
  username: michaelcalhoun
  password:

production:
  adapter: postgresql
  database: michaelcalhoun_production
  username: michaelcalhoun
  password:
